### GET all products
GET http://localhost:3000/admin/authors


### Create a product
POST http://localhost:3000/admin/authors
Content-Type: application/json

{
    "name_vol": "การหายตัวไป",
    "volume_no": "29",
    "description": "โดยมีเงื่อนงำซ่อนอยู่ในความทรงจำ",
    "price": 120
  }

### GET a product
GET http://localhost:3000/admin/authors

### Update a product
PUT http://localhost:3000/admin/authors
Content-Type: application/json


{
    "quantity": 99


  }

### Delete a product
DELETE  http://localhost:3000/admin/authors
Content-Type: application/json