### GET all products
GET http://localhost:3000/products


### Create a product
POST http://localhost:3000/products
Content-Type: application/json

 {
    "name_vol": "Dragon's Shadow Ascendant - Vol. 5: The Final Stand",
    "volume_no": "5",
    "description": "The epic conclusion to the saga.",
    "price": 35.00,
    "quantity": 150,
    "title_id": "6814725661fa18a1c47ce5a9",
    "author_id": "6814660761fa18a1c47ce560",
    "product_status": "available"
  }
### GET a product
GET http://localhost:3000/products/6819d659d64cf3a576089525

### Update a product
PUT http://localhost:3000/api/products/d0ec191d-9568-4c8a-ae72-c86193818679
Content-Type: application/json


{
    "quantity": 99


  }

### Delete a product
DELETE  http://localhost:3000/api/products/23eb08e4-f831-440f-82de-5693531bd37c
Content-Type: application/json

###GET NewRelease
GET http://localhost:3000/products/new-release
Content-Type: application/json