### GET user
GET http://localhost:3000/api/auth/get-all-users
Content-Type: application/json

### Register
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "email" : "beta@example.com",
    "password": "katsubook",
    "name": "Katsu",
    "lastName": "Kun",
    "dateOfBirth": "1999-01-02",
    "address": "11/111 KFC Pizza Pizza",
    "city": "Bangkok",
    "country": "Thailand",
    "phoneNumber": "091-234-5678"
}