### GET user
GET http://localhost:3000/api/auth/get-all-users
Content-Type: application/json


### Get user by Id
GET http://localhost:3000/api/auth/user/68166e9d10f7f60a2e5671be
Content-Type: application/json


### Register
POST http://localhost:3000/api/auth/register
Content-Type: application/json


{
    "email" : "Hellofortestpassword@example.com",
    "password": "katsubook",
    "name": "Katsu",
    "lastName": "testpassword",
    "dateOfBirth": "1999-02-02",
    "address": "11/111 KFC Hungry Hungry",
    "city_id": "68166dd9aa6c394d5a876c8e",
    "phoneNumber": "091-234-5679"
}




### login
POST http://localhost:3000/api/auth/login
Content-Type: application/json


{
    "email" : "Hellofortestpassword@example.com",
    "password": "katsubook"
}




### Update a user (some fields)
PATCH  http://localhost:3000/api/auth/user/68166e9d10f7f60a2e5671be
Content-Type: application/json


{
    "email" : "Hellofortestpassword2@example.com",
    "name": "KatsuOKmak",
    "lastName": "waipana",
    "dateOfBirth": "1999-02-03",
    "cityName": "Chiang Mai"
}


### Update a user (all fields)
PUT  http://localhost:3000/api/auth/user/68166e9d10f7f60a2e5671be
Content-Type: application/json


{
    "email" : "Hellofordelete@example.com",
    "password": "katsubook",
    "name": "Katsuokmakmak",
    "lastName": "waipana",
    "dateOfBirth": "1999-02-02",
    "address": "11/111 KFC Hungry Hungry",
    "city": "Bangkok",
    "country": "Thailand",
    "phoneNumber": "091-234-5679"
}

### Update Password
PATCH  http://localhost:3000/api/auth/user/68133c3d8e58fa3222fb7ad4/password
Content-Type: application/json

{
    "currentPassword" : "katsubook12",
    "newPassword": "katsubook"
}


### Delete a user
DELETE  http://localhost:3000/api/auth/user/681339109c200d2466674754
Content-Type: application/json


### Get all country
GET  http://localhost:3000/api/auth/country
Content-Type: application/json




