### GET user
GET http://localhost:3000/api/auth/get-all-users
Content-Type: application/json


### Get user by Id
GET http://localhost:3000/api/auth/user/680b9ac486b3842daeafca35
Content-Type: application/json


### Register
POST http://localhost:3000/api/auth/register
Content-Type: application/json


{
    "email" : "Hellofordelete@example.com",
    "password": "katsubook",
    "name": "Katsu",
    "lastName": "waipana",
    "dateOfBirth": "1999-02-02",
    "address": "11/111 KFC Hungry Hungry",
    "city": "Bangkok",
    "country": "Thailand",
    "phoneNumber": "091-234-5679"
}




### login
POST http://localhost:3000/api/auth/login
Content-Type: application/json


{
    "email" : "Hellowaiwaihi@example.com",
    "password": "katsubook"
}




### Update a user (some fields)
PATCH  http://localhost:3000/api/auth/user/680cff052a2d69dd87cb4024
Content-Type: application/json


{
    "email" : "Hellofordelete@example.com",
    "password": "katsubook",
    "name": "KatsuOK",
    "lastName": "waipana",
    "dateOfBirth": "1999-02-03"
}


### Update a user (all fields)
PUT  http://localhost:3000/api/auth/user/680cff052a2d69dd87cb4024
Content-Type: application/json


{
    "email" : "Hellofordelete@example.com",
    "password": "katsubook",
    "name": "Katsuokmakmak",
    "lastName": "waipana",
    "dateOfBirth": "1999-02-02",
    "address": "11/111 KFC Hungry Hungry",
    "city": "Bangkok",
    "country": "Thailand",
    "phoneNumber": "091-234-5679"
}






### Delete a user
DELETE  http://localhost:3000/api/auth/user/680cff052a2d69dd87cb4024
Content-Type: application/json






